---
language: ruby
sudo: false
cache: bundler
before_script:
  - bundle
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
  - bunlde exec rake beaker
  - bundle exec rake build
rvm:
  - 2.3.3
