---
language: ruby
sudo: required
cache: bundler
services:
  - docker
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
  - bundle exec rake beaker:centos7-docker
  - bundle exec rake build
rvm:
  - 2.3.3
